In [2]:
import numpy as np

In [5]:
example = np.arange (9).reshape (3,3)

In [6]:
example

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
example [:2,1:]

array([[1, 2],
       [4, 5]])

In [9]:
example [2:]

array([[6, 7, 8]])

In [10]:
example [2:,:]

array([[6, 7, 8]])

In [18]:

names=np.array(["anas","hassan","anas","hassan","behzad","anas"])

In [19]:
names

array(['anas', 'hassan', 'anas', 'hassan', 'behzad', 'anas'], dtype='<U6')

In [20]:
names=='anas'

array([ True, False,  True, False, False,  True])

In [26]:
data=np.random.randn (6,2)

In [27]:
data


array([[-1.15656926, -0.82639162],
       [ 0.37805549, -0.21005374],
       [ 0.88771992,  0.74085618],
       [ 0.13493614,  0.73104785],
       [-1.93855894,  1.01548987],
       [-0.77708899, -0.94276146]])

In [28]:
data[names=='anas']

array([[-1.15656926, -0.82639162],
       [ 0.88771992,  0.74085618],
       [-0.77708899, -0.94276146]])

In [30]:
example.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])